import type { Locale } from "./i18n";

const labels = {
  authorHint: ["Авторы — профили NIS Hub; у Telegram общий технический профиль", "Авторлар — NIS Hub профильдері; Telegram ортақ техникалық профильді қолданады", "Authors are NIS Hub profiles; Telegram uses a shared technical profile"],
  overview: ["Обзор", "Шолу", "Overview"], users: ["Пользователи", "Пайдаланушылар", "Users"], activity: ["Активность", "Белсенділік", "Activity"], homework: ["Домашние задания", "Үй тапсырмалары", "Homework"], schedule: ["Расписание", "Кесте", "Schedule"], content: ["Контент", "Мазмұн", "Content"], tickets: ["Поддержка", "Қолдау", "Support"], system: ["Система", "Жүйе", "System"],
  current: ["Текущее", "Ағымдағы", "Current"], imports: ["Импорт", "Импорт", "Import"], versions: ["Версии", "Нұсқалар", "Versions"], calendar: ["Календарь", "Күнтізбе", "Calendar"], classes: ["Классы", "Сыныптар", "Classes"], books: ["Книги", "Кітаптар", "Books"], subjects: ["Предметы", "Пәндер", "Subjects"], moderation: ["Модерация сообщества", "Қауымдастық модерациясы", "Community moderation"],
  control: ["Центр управления", "Басқару орталығы", "Control center"], hint: ["Данные и инструменты загружаются независимо. Доступ — только для admin.", "Деректер мен құралдар бөлек жүктеледі. Тек admin үшін.", "Data and tools load independently. Admin access only."],
  loading: ["Загрузка раздела…", "Бөлім жүктелуде…", "Loading section…"], unavailable: ["Данные недоступны. Проверьте подключение и admin-миграцию.", "Деректер қолжетімсіз. Қосылым мен admin миграциясын тексеріңіз.", "Data unavailable. Check the connection and admin migration."], empty: ["Записей пока нет.", "Жазбалар әлі жоқ.", "No records yet."], unknown: ["Неизвестно", "Белгісіз", "Unknown"], unnamed: ["Без имени", "Аты жоқ", "Unnamed"], noClass: ["Без класса", "Сыныпсыз", "No class"], all: ["Все", "Барлығы", "All"], search: ["Поиск по имени", "Аты бойынша іздеу", "Search name"], apply: ["Применить", "Қолдану", "Apply"], reset: ["Сбросить", "Тазарту", "Reset"], previous: ["Назад", "Артқа", "Previous"], next: ["Далее", "Келесі", "Next"], page: ["Страница", "Бет", "Page"],
  online: ["Онлайн · последние 15 минут", "Онлайн · соңғы 15 минут", "Online · last 15 minutes"], today: ["Активны сегодня", "Бүгін белсенді", "Active today"], week: ["Активны за 7 дней", "7 күнде белсенді", "Active in 7 days"], totalUsers: ["Всего пользователей", "Барлық пайдаланушылар", "Total users"], newUsers: ["Зарегистрированы сегодня", "Бүгін тіркелген", "New users today"], homeworkToday: ["ДЗ добавлено сегодня", "Бүгін қосылған ҮТ", "Homework added today"], openTickets: ["Открытые обращения", "Ашық өтініштер", "Open tickets"], errorsToday: ["Ошибки сегодня", "Бүгінгі қателер", "Errors today"], telemetry: ["Телеметрия ошибок не настроена", "Қате телеметриясы бапталмаған", "Error telemetry not configured"], status: ["Статус системы", "Жүйе күйі", "System status"], configuration: ["Проверка конфигурации, не uptime", "Конфигурация тексерісі, uptime емес", "Configuration check, not uptime"],
  chart: ["Активные пользователи по интервалам", "Аралықтардағы белсенді пайдаланушылар", "Active users by interval"], chartHint: ["Уникальные пользователи в каждом интервале; не просмотры страниц. Время: Oral.", "Әр аралықтағы бірегей пайдаланушылар; бет қаралымдары емес. Уақыт: Oral.", "Unique users per interval, not pageviews. Time zone: Oral."], classActivity: ["Активность классов", "Сынып белсенділігі", "Class activity"], registered: ["Зарегистрированы", "Тіркелген", "Registered"], recentUsers: ["Последние регистрации", "Соңғы тіркелулер", "Recent registrations"], recentActivity: ["Последние действия", "Соңғы әрекеттер", "Recent activity"], lastActivity: ["Последняя активность", "Соңғы белсенділік", "Last activity"], created: ["Дата регистрации", "Тіркелу күні", "Registered"], role: ["Роль", "Рөл", "Role"], student: ["Ученик", "Оқушы", "Student"], admin: ["Администратор", "Әкімші", "Admin"], detail: ["Подробнее", "Толығырақ", "Details"], publicProfile: ["Открыть публичный профиль", "Жария профильді ашу", "Open public profile"], saveUser: ["Сохранить класс и роль", "Сынып пен рөлді сақтау", "Save class and role"], confirmUser: ["Подтверждаю изменение класса и прав доступа этого пользователя", "Осы пайдаланушының сыныбы мен құқықтарын өзгертуге келісемін", "I confirm changing this user's class and permissions"], lastAdmin: ["Нельзя убрать последнего администратора.", "Соңғы әкімшіні алып тастауға болмайды.", "The last admin cannot be removed."], stale: ["Данные изменились. Обновите страницу и повторите.", "Деректер өзгерді. Бетті жаңартып, қайталаңыз.", "Data changed. Refresh and try again."], saved: ["Сохранено", "Сақталды", "Saved"],
  devices: ["Устройства · за 7 дней", "Құрылғылар · 7 күн", "Devices · 7 days"], browsers: ["Браузеры · за 7 дней", "Браузерлер · 7 күн", "Browsers · 7 days"], deviceHint: ["По последнему событию каждого пользователя. Только общие категории, без fingerprinting.", "Әр пайдаланушының соңғы оқиғасы бойынша. Тек жалпы санаттар, fingerprinting жоқ.", "Latest event per user. Coarse categories only; no fingerprinting."], refresh: ["Обновить", "Жаңарту", "Refresh"],
  due: ["Дата задания", "Тапсырма күні", "Due date"], source: ["Источник", "Дереккөз", "Source"], telegram: ["Telegram · подтверждён", "Telegram · расталған", "Telegram · verified"], sourceUnknown: ["Источник не зафиксирован", "Дереккөз тіркелмеген", "Origin not recorded"], sourceHint: ["Telegram определяется только по записи успешной публикации бота. Остальные источники неизвестны; created_by не считается доказательством.", "Telegram тек боттың сәтті жариялау жазбасынан анықталады. Басқа дереккөздер белгісіз; created_by дәлел емес.", "Telegram requires a successful bot publication record. Other origins are unknown; created_by is not proof."], visible: ["Видимые", "Көрінетін", "Visible"], hidden: ["Скрытые", "Жасырылған", "Hidden"], moderationStatus: ["Модерация", "Модерация", "Moderation"], authors: ["Уникальные авторы", "Бірегей авторлар", "Unique authors"], addedWeek: ["Добавлено за 7 дней", "7 күнде қосылған", "Added in 7 days"], hide: ["Скрыть", "Жасыру", "Hide"], confirmHide: ["Подтверждаю скрытие задания для учеников", "Тапсырманы оқушылардан жасыруға келісемін", "I confirm hiding this homework from students"], addHomework: ["Добавить через существующую форму класса", "Сыныптың бар формасы арқылы қосу", "Add through the existing class form"], hideHint: ["Существующая модерация поддерживает скрытие, но не восстановление. Удалённые задания не показаны.", "Қазіргі модерация жасыруды қолдайды, қалпына келтіруді емес. Жойылған тапсырмалар көрсетілмейді.", "Existing moderation supports hiding, not restoring. Deleted homework is excluded."], body: ["Полный текст", "Толық мәтін", "Full text"],
  unread: ["Ожидают ответа admin", "Admin жауабын күтуде", "Waiting for admin"], resolved: ["Решены сегодня", "Бүгін шешілген", "Resolved today"], resolvedHint: ["Уникальные обращения с переходом в resolved сегодня", "Бүгін resolved күйіне өткен бірегей өтініштер", "Distinct tickets transitioned to resolved today"],
  health: ["Сервисы", "Қызметтер", "Services"], configured: ["Настроено · работа не проверена", "Бапталған · жұмысы тексерілмеген", "Configured · operation not verified"], missing: ["Не настроено", "Бапталмаған", "Not configured"], reachable: ["Запрос к базе выполнен", "Дерекқор сұрауы орындалды", "Database query succeeded"], failed: ["Проверка недоступна", "Тексеру қолжетімсіз", "Check unavailable"], version: ["Версия production", "Production нұсқасы", "Production version"], commit: ["Commit", "Commit", "Commit"], built: ["Время сборки", "Құрастыру уақыты", "Build time"], performance: ["Производительность", "Өнімділік", "Performance"], noMetrics: ["Измеряемые runtime-метрики не подключены. Скорость переходов проверяется в browser QA; это не production latency.", "Runtime метрикалары қосылмаған. Ауысу browser QA арқылы тексеріледі; бұл production latency емес.", "Runtime metrics are not connected. Navigation is checked in browser QA, not reported as production latency."],
  openedHome: ["Открыл главную", "Басты бетті ашты", "Opened Home"], openedSchedule: ["Открыл расписание", "Кестені ашты", "Opened schedule"], openedProfile: ["Открыл профиль", "Профильді ашты", "Opened profile"], openedLibrary: ["Открыл библиотеку", "Кітапхананы ашты", "Opened library"], openedBook: ["Открыл книгу", "Кітапты ашты", "Opened book"], openedDiary: ["Открыл дневник", "Күнделікті ашты", "Opened diary"], openedCommunity: ["Открыл сообщество", "Қауымдастықты ашты", "Opened Community"], openedSupport: ["Открыл поддержку", "Қолдауды ашты", "Opened support"], openedAdmin: ["Открыл админ-панель", "Admin панелін ашты", "Opened admin"], openedSection: ["Открыл раздел приложения", "Қолданба бөлімін ашты", "Opened app section"], activityHint: ["Трекер фиксирует открытия разделов, а не выполнение действий. Добавление ДЗ и вызовы AI не выводятся как события без подтверждения.", "Трекер бөлім ашылуын тіркейді, әрекет орындалуын емес. ҮТ қосу мен AI шақыруы расталмай оқиға деп көрсетілмейді.", "The tracker records section opens, not completed actions. Homework creation and AI calls are not claimed without event evidence."],
  bookSearch: ["Название книги", "Кітап атауы", "Book title"], publication: ["Публикация", "Жариялау", "Publication"], grade: ["Параллель", "Сынып деңгейі", "Grade"],
} as const;
export function controlCopy(locale: Locale) {
  const index = locale === "ru" ? 0 : locale === "kk" ? 1 : 2;
  return Object.fromEntries(Object.entries(labels).map(([key, values]) => [key, values[index]])) as Record<keyof typeof labels, string>;
}
export const adminSections = ["overview", "users", "activity", "homework", "schedule", "content", "tickets", "system"] as const;
export type AdminSection = typeof adminSections[number];
export function adminHref(section: AdminSection) { return section === "overview" ? "/admin" : `/admin/${section}`; }
export function activityLabel(path: string, locale: Locale) {
  const p = path.split(/[?#]/, 1)[0], t = controlCopy(locale);
  if (p === "/") return t.openedHome;
  if (p === "/schedule") return t.openedSchedule;
  if (p === "/profile" || p.startsWith("/people/")) return t.openedProfile;
  if (p === "/library") return t.openedLibrary;
  if (/^\/books\/[\da-f-]+(?:\/read)?$/i.test(p)) return t.openedBook;
  if (p === "/diary") return t.openedDiary;
  if (["/messages", "/people", "/friends"].includes(p)) return t.openedCommunity;
  if (p === "/support" || p.startsWith("/support/")) return t.openedSupport;
  if (p === "/admin" || p.startsWith("/admin/")) return t.openedAdmin;
  return t.openedSection;
}
export type Device = "iPhone/iOS" | "Android" | "Mac" | "Windows" | "Other";
export type Browser = "Safari" | "Chrome" | "Firefox" | "Edge" | "Other";
export function coarseAgent(value: string | null | undefined): { device: Device; browser: Browser } {
  const ua = (value ?? "").slice(0, 255);
  const device = /iPhone|iPad|iPod/i.test(ua) ? "iPhone/iOS" : /Android/i.test(ua) ? "Android" : /Macintosh|Mac OS/i.test(ua) ? "Mac" : /Windows/i.test(ua) ? "Windows" : "Other";
  const browser = /Edg(?:e|A|iOS)?\//i.test(ua) ? "Edge" : /Firefox|FxiOS/i.test(ua) ? "Firefox" : /Chrome|CriOS|Chromium/i.test(ua) ? "Chrome" : /Safari/i.test(ua) ? "Safari" : "Other";
  return { device, browser };
}
export function adminTime(value: string | null, locale: Locale) {
  if (!value || !Number.isFinite(new Date(value).getTime())) return "—";
  return new Intl.DateTimeFormat(locale === "kk" ? "kk-KZ" : locale, { timeZone: "Asia/Oral", month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
}
export function adminPage(value?: string) { const n = Number(value ?? 0); return Number.isInteger(n) && n >= 0 && n <= 400 ? n : 0; }
