import type { Locale } from "./i18n";
const copy = {
  ru: {
    messages: "Сообщения",
    diary: "Дневник",
    notifications: "Уведомления",
    newMessage: "Новое сообщение",
    from: "От",
    close: "Закрыть",
    read: "Прочитано",
    markRead: "Отметить прочитанным",
    noNotifications: "Новых уведомлений нет",
    noThreads: "Переписок пока нет",
    newChat: "Начать переписку",
    recipient: "Имя получателя",
    exactName: "Введите точное отображаемое имя. Регистр не важен.",
    start: "Открыть чат",
    send: "Отправить",
    message: "Сообщение",
    chooseChat: "Выберите переписку или найдите собеседника по имени.",
    emptyChat: "Напишите первое сообщение.",
    older: "Предыдущие сообщения",
    loading: "Загрузка…",
    failed: "Не удалось загрузить данные. Повторите попытку.",
    sendFailed: "Сообщение не отправлено. Текст сохранён, попробуйте ещё раз.",
    unavailable: "Получатель не найден или это ваше имя.",
    nameRequired: "Сначала задайте отображаемое имя в профиле.",
    nameTaken: "Это имя уже занято. Выберите другое.",
    nameHint:
      "Уникальное имя для ЛС. Другие ученики могут найти вас по нему; класс и любимые предметы остаются приватными.",
    migration:
      "Личные сообщения ещё не подключены. Администратору нужно применить миграцию базы данных.",
    retry: "Повторить",
    rate: "Слишком много действий. Попробуйте чуть позже.",
    privateChat: "Переписка доступна только вам и собеседнику.",
    demo: "Демо-дневник",
    demoHint:
      "Пример оценок, не ваши школьные данные. Прямое подключение к sms.nis.ura.kz пока не настроено.",
    importHint:
      "Импортируйте сохранённую HTML-таблицу или CSV: subject, date, score, max, type. Файл обрабатывается только в браузере и не отправляется на сервер.",
    importFile: "Импорт оценок",
    sample: "Загрузить пример",
    imported: "Импортировано локально",
    subject: "Предмет",
    score: "Баллы",
    date: "Дата",
    type: "Вид работы",
    results: "Результаты работ",
    average: "Средний результат работ",
    notOfficial:
      "Это среднее процентов за работы, не официальная четвертная оценка.",
    noGrades: "Оценок нет",
    badImport:
      "Таблица не распознана. Нужны предмет, дата, балл и максимум; проверьте формат и диапазоны.",
    importedCount: "Работ",
    quarter: "Все предметы",
    clear: "Очистить",
    cover: "Первая страница",
    coverFailed: "Предпросмотр недоступен",
    coverRetry: "Загрузить обложку",
    aiHelp: "Помощник по выбранным страницам",
    webOnly: "Уведомления внутри сайта. Вкладка должна быть открыта.",
    dmError: "Не удалось выполнить действие.",
    changeAvatar: "Изменить аватар",
  },
  kk: {
    messages: "Хабарламалар",
    diary: "Күнделік",
    notifications: "Хабарландырулар",
    newMessage: "Жаңа хабарлама",
    from: "Кімнен",
    close: "Жабу",
    read: "Оқылды",
    markRead: "Оқылды деп белгілеу",
    noNotifications: "Жаңа хабарландыру жоқ",
    noThreads: "Әзірге хат алмасу жоқ",
    newChat: "Хат алмасуды бастау",
    recipient: "Алушының есімі",
    exactName:
      "Нақты көрсетілетін есімді енгізіңіз. Әріп регистрі маңызды емес.",
    start: "Чатты ашу",
    send: "Жіберу",
    message: "Хабарлама",
    chooseChat: "Хат алмасуды таңдаңыз немесе есімі бойынша адамды табыңыз.",
    emptyChat: "Алғашқы хабарламаны жазыңыз.",
    older: "Алдыңғы хабарламалар",
    loading: "Жүктелуде…",
    failed: "Деректер жүктелмеді. Қайталап көріңіз.",
    sendFailed: "Хабарлама жіберілмеді. Мәтін сақталды, қайталап көріңіз.",
    unavailable: "Алушы табылмады немесе бұл сіздің есіміңіз.",
    nameRequired: "Алдымен профильде көрсетілетін есімді енгізіңіз.",
    nameTaken: "Бұл есім бос емес. Басқасын таңдаңыз.",
    nameHint:
      "Жеке хабарламаларға арналған бірегей есім. Басқа оқушылар сізді осы есіммен таба алады; сынып пен сүйікті пәндер жеке қалады.",
    migration:
      "Жеке хабарламалар әлі қосылмаған. Әкімші дерекқор миграциясын қолдануы керек.",
    retry: "Қайталау",
    rate: "Әрекет тым көп. Сәл кейінірек көріңіз.",
    privateChat: "Хат алмасуды тек сіз және сұхбаттасыңыз көре аласыз.",
    demo: "Демо-күнделік",
    demoHint:
      "Бұл сіздің бағаларыңыз емес, үлгі деректер. sms.nis.ura.kz сайтына тікелей қосылу әлі бапталмаған.",
    importHint:
      "Сақталған HTML кестесін немесе CSV файлын импорттаңыз: subject, date, score, max, type. Файл тек браузерде өңделеді, серверге жіберілмейді.",
    importFile: "Бағаларды импорттау",
    sample: "Үлгіні жүктеу",
    imported: "Жергілікті импорт",
    subject: "Пән",
    score: "Балл",
    date: "Күні",
    type: "Жұмыс түрі",
    results: "Жұмыс нәтижелері",
    average: "Жұмыстардың орташа нәтижесі",
    notOfficial:
      "Бұл жұмыстар пайыздарының орташа мәні, ресми тоқсандық баға емес.",
    noGrades: "Бағалар жоқ",
    badImport:
      "Кесте танылмады. Пән, күн, балл және ең жоғары балл қажет; пішім мен мәндерді тексеріңіз.",
    importedCount: "Жұмыс",
    quarter: "Барлық пәндер",
    clear: "Тазарту",
    cover: "Бірінші бет",
    coverFailed: "Алдын ала қарау қолжетімсіз",
    coverRetry: "Мұқабаны жүктеу",
    aiHelp: "Таңдалған беттер бойынша көмекші",
    webOnly: "Сайт ішіндегі хабарландырулар. Қойынды ашық болуы керек.",
    dmError: "Әрекет орындалмады.",
    changeAvatar: "Аватарды өзгерту",
  },
  en: {
    messages: "Messages",
    diary: "Diary",
    notifications: "Notifications",
    newMessage: "New message",
    from: "From",
    close: "Close",
    read: "Read",
    markRead: "Mark as read",
    noNotifications: "No new notifications",
    noThreads: "No conversations yet",
    newChat: "Start a conversation",
    recipient: "Recipient name",
    exactName: "Enter their exact display name. Matching is case insensitive.",
    start: "Open chat",
    send: "Send",
    message: "Message",
    chooseChat: "Choose a conversation or find someone by name.",
    emptyChat: "Write the first message.",
    older: "Earlier messages",
    loading: "Loading…",
    failed: "Could not load data. Try again.",
    sendFailed: "Message not sent. Your text is preserved; try again.",
    unavailable: "Recipient not found, or you entered your own name.",
    nameRequired: "First set your display name in your profile.",
    nameTaken: "This name is taken. Choose another.",
    nameHint:
      "A unique name for DMs. Other students can find you by this name; your class and favourite subjects stay private.",
    migration:
      "Direct messages are not connected yet. An administrator must apply the database migration.",
    retry: "Retry",
    rate: "Too many actions. Try again shortly.",
    privateChat: "Only you and your recipient can access this conversation.",
    demo: "Demo diary",
    demoHint:
      "Sample grades, not your school records. A direct connection to sms.nis.ura.kz is not configured yet.",
    importHint:
      "Import a saved HTML table or CSV: subject, date, score, max, type. The file is processed in your browser only and is not uploaded.",
    importFile: "Import grades",
    sample: "Load sample",
    imported: "Imported locally",
    subject: "Subject",
    score: "Score",
    date: "Date",
    type: "Assessment",
    results: "Assessment results",
    average: "Average assessment result",
    notOfficial:
      "An average of assessment percentages, not an official term grade.",
    noGrades: "No grades",
    badImport:
      "Table not recognised. Subject, date, score and maximum are required; check the format and ranges.",
    importedCount: "Assessments",
    quarter: "All subjects",
    clear: "Clear",
    cover: "First page",
    coverFailed: "Preview unavailable",
    coverRetry: "Load cover",
    aiHelp: "Help with the selected pages",
    webOnly: "In-site notifications. Keep the tab open.",
    dmError: "Could not complete the action.",
    changeAvatar: "Change avatar",
  },
};
export const communityCopy = (locale: Locale) => copy[locale];
