import type { Person } from "./people";
export type DmThread = {peer_id:string;last_deleted:boolean;blocked:boolean;id:string;peer_name:string;last_body:string|null;last_at:string;unread:number};
export type DirectMessage = {deleted_at:string|null;id:string;thread_id:string;sender_id:string;body:string;client_id:string;created_at:string};
export type WebNotification = {body_preview:string;id:string;thread_id:string;actor_name:string;created_at:string;read_at:string|null};
export type Profile = { id: string; display_name: string | null; class_id: string | null; avatar_path: string | null; bio: string | null; role: "student" | "admin"; created_at: string; updated_at: string };
export type ClassRow = { id: string; name: string; grade: number | null; section: string | null; created_at: string };
export type SubjectRow = { id: string; name: string; name_ru?: string | null; name_kz: string | null; name_en: string | null; short_name: string | null; created_at: string };
export type Book = { id: string; title: string; subject_id: string; class_id: string | null; grade: number | null; author: string | null; publisher: string | null; publication_year: number | null; language: string | null; cover_path: string | null; file_path: string; page_count: number | null; publication_status: "draft" | "published" | "archived"; created_at: string; updated_at: string };
export type BookVariant = {id:string;book_id:string;language:"ru"|"kz"|"en"|"und";storage_path:string;cover_path:string|null;file_size:number|null;page_count:number|null;publication_status:Book["publication_status"];content_revision:string;created_at:string;updated_at:string};
export type VariantBookmark = {id:string;profile_id:string;book_variant_id:string;page_number:number;created_at:string};
export type VariantProgress = {profile_id:string;book_variant_id:string;page_number:number;updated_at:string};
export type BookPage = {id:string;book_variant_id:string;content_revision:string;page_number:number;text:string;extraction_status:"ready"|"empty";text_hash:string;created_at:string};
export type BookExtraction = {book_variant_id:string;content_revision:string;job_id:string;status:"extracting"|"ready"|"failed";page_count:number|null;file_hash:string|null;started_at:string;finished_at:string|null};
export type AiGeneration = {id:string;user_id:string;book_variant_id:string;content_revision:string;start_page:number;end_page:number;mode:string;locale:string;source_hash:string;model_key:string;status:"pending"|"ready"|"failed";response:string|null;signature:string|null;lease:string;created_at:string};
export type Bookmark = { id: string; profile_id: string; book_id: string; page_number: number; created_at: string };
export type Progress = { profile_id: string; book_id: string; page_number: number; updated_at: string };
export type Lesson = { id: string; class_id: string; date: string; lesson_number: number; subject_id: string; teacher: string | null; room: string | null; created_at: string };
export type WeeklyLesson = { subgroup_key?: string; subgroup_label?: string | null; audience?: string; id: string; class_id: string; weekday: number; lesson_start: number; lesson_end: number; start_time: string | null; end_time: string | null; subject_id: string; teacher: string | null; room: string | null; effective_from: string | null; effective_to: string | null; created_at: string; updated_at: string };
export type EduPageState = {id:boolean;aliases:Json;last_checked:string|null;last_synced:string|null;last_error:string|null;publication:string|null;version_id:string|null};
export type NonSchoolDay = {id:string;start_date:string;end_date:string;type:"holiday"|"vacation"|"cancelled"|"other";label:string;created_by:string|null;created_at:string};
export type ScheduleVersion = {id:string;created_at:string;created_by:string|null;source_type:"baseline"|"csv_tsv"|"delete"|"restore"|"edupage";row_count:number;note:string;status:"active"|"superseded";previous_id:string|null;restored_from:string|null;snapshot:Json};
export type TicketCategory = "platform"|"schedule"|"library"|"account"|"data"|"other";
export type TicketStatus = "open"|"in_progress"|"resolved"|"closed";
export type SupportTicket = {id:string;owner_id:string;category:TicketCategory;title:string;description:string;status:TicketStatus;created_at:string;updated_at:string;last_user_message_at:string;last_admin_message_at:string|null;needs_admin_reply:boolean};
export type SupportMessage = {id:string;ticket_id:string;author_id:string|null;author_role:"student"|"admin";body:string;created_at:string};
export type SupportStatusEvent = {id:string;ticket_id:string;actor_id:string|null;previous_status:TicketStatus;status:TicketStatus;created_at:string};
export type ClassHomework={id:string;class_id:string;subject_id:string;due_date:string;body:string;created_by:string;created_at:string;updated_at:string;deleted_at:string|null;moderation_status:"visible"|"hidden"};
export type CommunityReport={id:string;reporter_id:string;target_kind:"profile"|"message"|"homework";target_id:string;reason:"spam"|"harassment"|"privacy"|"other";detail:string;status:"open"|"resolved";created_at:string;resolved_at:string|null;resolved_by:string|null};
export type TaskPriority="low"|"medium"|"high"|"urgent";
export type TaskStatus="active"|"completed"|"archived";
export type PersonalTask={id:string;owner_id:string;subject_id:string|null;title:string;notes:string;priority:TaskPriority;status:TaskStatus;due_at:string|null;remind_at:string|null;reminder_read_at:string|null;completed_at:string|null;created_at:string;updated_at:string};
export type TaskReminder={id:string;task_id:string;title:string;priority:TaskPriority;due_at:string;remind_at:string;read_at:string|null};
export type AppNotification={id:string;kind:"message"|"task";href:string;title:string;body_preview:string;created_at:string;read_at:string|null;thread_id?:string;task_id?:string;priority?:TaskPriority;due_at?:string};
type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
type Table<Row, Required extends keyof Row> = { Row: Row; Insert: Pick<Row, Required> & Partial<Row>; Update: Partial<Row>; Relationships: [] };
// Application types for schema.sql and migrations through v0.5. Historical
// rights tables/enums are retained only for schema compatibility. Regenerate from the
// owner's Supabase project after applying migrations; no cloud schema is assumed.
export type Database = { public: {
  Tables: {
    edupage_sync_state: Table<EduPageState, "id">;
    sms_sessions: Table<{user_id:string;id:string;ciphertext:string;expires_at:string;created_at:string},"user_id"|"ciphertext"|"expires_at">;
    class_homework:Table<ClassHomework,"class_id"|"subject_id"|"due_date"|"body"|"created_by">;
    personal_tasks:Table<PersonalTask,"owner_id"|"title">;
    community_reports:Table<CommunityReport,"reporter_id"|"target_kind"|"target_id"|"reason">;
    direct_messages: Table<DirectMessage,"thread_id"|"sender_id"|"body"|"client_id">;
    web_notifications: Table<{id:string;recipient_id:string;actor_id:string;thread_id:string;message_id:string;created_at:string;read_at:string|null},"recipient_id"|"actor_id"|"thread_id"|"message_id">;
    schedule_import_batches: Table<ScheduleVersion, "source_type"|"row_count"|"status"|"snapshot">;
    non_school_days: Table<NonSchoolDay, "start_date"|"end_date"|"type"|"label">;
    support_tickets: Table<SupportTicket, "owner_id"|"category"|"title"|"description">;
    support_messages: Table<SupportMessage, "ticket_id"|"author_role"|"body">;
    support_status_events: Table<SupportStatusEvent, "ticket_id"|"previous_status"|"status">;
    profiles: Table<Profile, "id">;
    classes: Table<ClassRow, "name">;
    subjects: Table<SubjectRow, "name">;
    book_pages: Table<BookPage,"book_variant_id"|"content_revision"|"page_number"|"text"|"text_hash"|"extraction_status">;
    book_extractions: Table<BookExtraction,"book_variant_id"|"content_revision"|"status">;
    ai_study_generations: Table<AiGeneration,"user_id"|"book_variant_id"|"content_revision"|"start_page"|"end_page"|"mode"|"locale"|"source_hash"|"model_key"|"status">;
    book_variants: Table<BookVariant,"book_id"|"language"|"storage_path">;
    variant_bookmarks: Table<VariantBookmark,"profile_id"|"book_variant_id"|"page_number">;
    variant_reading_progress: Table<VariantProgress,"profile_id"|"book_variant_id"|"page_number">;
    books: Table<Book, "title" | "subject_id" | "file_path">;
    bookmarks: Table<Bookmark, "profile_id" | "book_id" | "page_number">;
    reading_progress: Table<Progress, "profile_id" | "book_id" | "page_number">;
    weekly_schedule: Table<WeeklyLesson, "class_id" | "weekday" | "lesson_start" | "lesson_end" | "subject_id">;
    schedule: Table<Lesson, "class_id" | "date" | "lesson_number" | "subject_id">;
    profile_top_subjects: Table<{ profile_id: string; subject_id: string; position: number }, "profile_id" | "subject_id" | "position">;
    book_rights: Table<{ book_id: string; source: string; permission_note: string }, "book_id" | "source" | "permission_note">;
  };
  Views: Record<string, never>;
  Functions: {
    sync_edupage_schedule:{Args:{p_lessons:Json;p_classes:string[];p_expected_active:string;p_note:string;p_aliases:Json};Returns:string};
    save_sms_session:{Args:{p_ciphertext:string;p_expires:string};Returns:string};
    save_class_homework:{Args:{p_subject:string;p_due:string;p_body:string;p_id?:string|null};Returns:string};
    delete_class_homework:{Args:{p_id:string};Returns:undefined};
    moderate_class_homework:{Args:{p_id:string};Returns:undefined};
    set_user_block:{Args:{p_peer:string;p_blocked:boolean};Returns:undefined};
    set_dm_hidden:{Args:{p_thread:string;p_hidden:boolean};Returns:undefined};
    delete_own_dm:{Args:{p_message:string};Returns:undefined};
    dm_inbox_v053:{Args:Record<string,never>;Returns:DmThread[]};
    dm_history_v053:{Args:{p_thread:string;p_before?:string|null;p_id?:string|null};Returns:DirectMessage[]};
    notification_unread_v053:{Args:Record<string,never>;Returns:number};
    notification_feed_v053:{Args:Record<string,never>;Returns:WebNotification[]};
    report_community:{Args:{p_kind:string;p_target:string;p_reason:string;p_detail:string};Returns:string};
    resolve_community_report:{Args:{p_id:string};Returns:undefined};
    community_report_context:{Args:{p_id:string};Returns:string|null};
    people_list:{Args:{p_scope?:string;p_query?:string;p_id?:string|null;p_offset?:number};Returns:Person[]};
    friend_action:{Args:{p_peer:string;p_action:string};Returns:undefined};
    save_profile_v053:{Args:{p_name:string;p_class:string|null;p_subjects:string[];p_bio:string};Returns:undefined};
    start_dm:{Args:{p_name:string};Returns:string};
    send_dm:{Args:{p_thread:string;p_body:string;p_client:string};Returns:string};
    dm_inbox:{Args:Record<string,never>;Returns:DmThread[]};
    read_dm:{Args:{p_thread:string;p_message:string};Returns:undefined};
    notification_feed:{Args:Record<string,never>;Returns:WebNotification[]};
    dismiss_notification:{Args:{p_id:string};Returns:undefined};
    save_personal_task:{Args:{p_id:string|null;p_title:string;p_notes:string;p_priority:TaskPriority;p_subject:string|null;p_due:string|null;p_remind:string|null};Returns:string};
    set_personal_task_status:{Args:{p_id:string;p_status:TaskStatus};Returns:undefined};
    snooze_personal_task:{Args:{p_id:string;p_minutes:number};Returns:undefined};
    task_notification_feed:{Args:Record<string,never>;Returns:TaskReminder[]};
    task_notification_unread:{Args:Record<string,never>;Returns:number};
    dismiss_task_notification:{Args:{p_id:string};Returns:undefined};
    create_support_ticket: {Args:{p_category:string;p_title:string;p_description:string};Returns:string};
    reply_support_ticket: {Args:{p_ticket:string;p_body:string};Returns:string};
    set_support_status: {Args:{p_ticket:string;p_status:string};Returns:undefined};
    is_admin: { Args: Record<string, never>; Returns: boolean };
    save_profile: { Args: { p_name: string; p_class: string | null; p_subjects: string[] }; Returns: undefined };
    delete_weekly_lesson: {Args:{p_id:string};Returns:undefined};
    restore_schedule_version: {Args:{p_id:string;p_expected_active:string};Returns:string};
    import_weekly_schedule: { Args: { p_lessons: Json }; Returns: number };
    import_schedule: { Args: { p_lessons: Json }; Returns: number };
    begin_book_extraction:{Args:{p_variant:string};Returns:Json};
    put_book_pages:{Args:{p_variant:string;p_revision:string;p_job:string;p_pages:Json};Returns:undefined};
    finish_book_extraction:{Args:{p_variant:string;p_revision:string;p_job:string;p_count:number;p_hash:string;p_failed?:boolean};Returns:undefined};
    reserve_ai_study:{Args:{p_variant:string;p_revision:string;p_start:number;p_end:number;p_mode:string;p_locale:string;p_hash:string;p_model:string;p_limit?:number};Returns:Json};
    complete_ai_study:{Args:{p_id:string;p_lease:string;p_response:string;p_signature:string;p_failed?:boolean};Returns:boolean};
    save_book_edition: {Args:{p_book:Json;p_variant:Json;p_prepare?:boolean};Returns:string};
    save_book: { Args: { p_book: Json }; Returns: string };
  };
  Enums: { profile_role: "student" | "admin"; book_publication_status: Book["publication_status"]; book_license_status: "pending_review" | "approved" | "restricted" };
  CompositeTypes: Record<string, never>;
} };
