import type {Locale} from "./i18n";
import {supportLegalCopy} from "./support-legal-copy";
import {v053Legal} from "./v053-legal-copy";

export const serviceOperator={name:"Есентаев Т.",email:"sun97794546@gmail.com"};
type LegalCopy={label:string;intro:string;revision:string;privacyTitle:string;termsTitle:string;privacy:[string,string][];terms:[string,string][]};
const contact=serviceOperator.name+" · "+serviceOperator.email;
export const legalCopy:Record<Locale,LegalCopy>={
 ru:{
 label:"Информация о сервисе",intro:"Как NIS Hub работает с вашими данными и какие правила действуют при использовании сервиса.",
 revision:"Обновлено: 26.09.2026.",privacyTitle:"Политика конфиденциальности",termsTitle:"Условия использования",
 privacy:[
 ["Оператор и связь",contact+". По вопросам персональных данных и удаления свяжитесь с оператором по этому email. Не присылайте пароль, ИИН, токены или подписанные ссылки. Перед выполнением запроса может потребоваться подтверждение принадлежности аккаунта."],
 ["Аккаунт и профиль","Supabase Auth обрабатывает email, пароль и сессию для входа. Supabase хранит идентификатор аккаунта, отображаемое имя, класс, Bio, Top 4 предмета, роль, даты изменений и путь аватара. Имя, Bio и Top 4 доступны другим вошедшим участникам; email, класс, история чтения и обращения не входят в публичный профиль."],
 ["Аватар, закладки и чтение","Аватар хранится в приватном Supabase Storage по пути <uid>/avatar.webp. Изображение преобразуется в WebP без исходных метаданных, новая загрузка заменяет прежний файл. Другие участники видят инициалы, а не приватный аватар. Закладки и последняя страница сохраняются по пользователю и варианту учебника. Временные подписанные ссылки дают ограниченный по времени доступ к разрешённым файлам; не передавайте их другим."],
 ["Настройки и технические данные","Cookies Supabase поддерживают вход и обновление сессии. Cookie nis-locale хранит язык до года; localStorage nis-theme и nis-sidebar сохраняют тему и состояние панели до изменения или очистки. Фильтры Library отражаются в URL и могут остаться в истории браузера. Диагностика входа NIS Hub записывает только безопасную категорию, код и статус ошибки, без email, пароля, cookies и токенов. Хостинг может вести собственные технические журналы."],
 ["Хостинг и расписание","Vercel размещает приложение; Supabase предоставляет Auth, базу и приватный Storage. Сервер получает разрешённое расписание EduPage; администраторы проверяют и публикуют его, также доступен CSV/TSV-импорт. В базе остаются версии расписания, календарь и история административных действий. Пароль SMS для EduPage не используется. PDF.js, шрифты и предметные иллюстрации загружаются с сайта; иллюстрации не являются обложками учебников."],
 ["Необязательный SMS-дневник","По вашему запросу ИИН и пароль временно обрабатываются сервером NIS Hub и передаются по HTTPS школьной системе sms.ura.nis.edu.kz. Они не сохраняются в базе, браузерном хранилище или журналах приложения. Cookies SMS шифруются AES-256-GCM и привязываются к аккаунту; сессия действует максимум 30 минут либо меньше по сроку SMS. Она хранится в HttpOnly cookie; большие шифрованные сессии — в Supabase с TTL и непрозрачным идентификатором в cookie. Отключение удаляет локальную сессию и доступную серверную запись. Оценки находятся в памяти сервера/страницы, не сохраняются в базе NIS Hub и не отправляются в Gemini или Telegram."],
 ["Необязательный AI Study","При запуске AI сервер отправляет Google Gemini текст выбранных страниц, режим и язык — не всю библиотеку, профиль, email, пароль или подписанные URL. Проверка ответов дополнительно передаёт исходные вопросы и ваши ответы. Текст PDF извлекается по страницам в Supabase; генерации кэшируются с владельцем, вариантом книги, диапазоном, хэшем источника и ответом. Метаданные попыток обеспечивают лимиты. Ответы пользователя и обратная связь самопроверки остаются в памяти вкладки, не сохраняются NIS Hub и не журналируются. Действуют условия выбранного тарифа Gemini: на бесплатном тарифе материалы могут использоваться для улучшения сервисов и проверяться людьми. Не выбирайте конфиденциальный текст."],
 ["Задачи, сообщения и уведомления","Supabase хранит личные задачи, заметки, важность, сроки, время напоминаний и статус выполнения; они доступны только владельцу. Supabase также хранит участников переписки, тексты, время и отметки прочтения. Переписка доступна её участникам; сквозного шифрования нет. Напоминания показываются в NIS Hub и, после явного разрешения, в браузере, пока сайт открыт; фоновых push-уведомлений при полностью закрытом сайте нет."],
 ["Хранение и удаление","Данные хранятся столько, сколько необходимо для работы соответствующей функции и выполнения запросов пользователя. Фиксированные общие сроки хранения и обработки запросов пока не утверждены. Вы можете исправлять профиль, удалять закладки и запросить удаление аккаунта/данных по указанному контакту. Автоматического самостоятельного удаления аккаунта нет. Оператор проверяет принадлежность аккаунта, связанные записи и отдельно файлы Storage; журналы, Telegram и резервные копии требуют отдельной проверки. Сроки технических журналов и резервных копий зависят от действующих настроек провайдеров; немедленное удаление всех копий не обещается."],
 ["Аудитория и безопасность","NIS Hub предназначен для совершеннолетних пользователей 18+. Технической проверки возраста в приложении нет. Не вводите лишние персональные сведения или чужие данные. Приватный Storage и правила доступа ограничивают доступ в приложении, но не являются DRM и не исключают технический доступ администратора инфраструктуры."]
 ],
 terms:[
 ["Назначение и оператор","NIS Hub помогает работать с учебными материалами, расписанием и личным учебным пространством. Оператор: "+contact+". Это самостоятельный сервис; официальное представительство школы или сети НИШ не заявляется."],
 ["Аккаунт","Сервис предназначен для пользователей 18+. Используйте собственный аккаунт, защищайте пароль и доступ к email, не передавайте сессию другим. О подозрении на компрометацию сообщите оператору без передачи секретов."],
 ["Материалы","Доступ предоставляется только к опубликованным разрешённым материалам с проверкой авторизации. Получение доступа не передаёт авторские права. Не публикуйте приватные ссылки или копии без соответствующего разрешения."],
 ["Расписание и SMS","Проверяйте важные изменения расписания у школы. Подключайте только свой разрешённый SMS-аккаунт. NIS Hub показывает доступные данные школьного сервиса; расчётные проценты явно отмечены и не являются официальной итоговой оценкой. Доступность зависит также от работы школьных систем."],
 ["AI и ограничения","AI Study — необязательный учебный помощник по выбранному источнику, не официальный экзаменатор. Ответ может быть неполным или ошибочным: проверяйте источник и цитаты. Действуют ограничения диапазона и частоты запросов; доступность зависит от провайдера. Не передавайте конфиденциальные материалы."],
 ["Доступность и обращения","Сервис может быть недоступен во время сбоев или обслуживания. Администраторы могут ограничивать злоупотребления через существующие средства модерации. По вопросам данных и удаления используйте "+serviceOperator.email+". Конкретный срок ответа не установлен; не отправляйте в обращении пароль или токены."]
 ]},
 kk:{
 label:"Сервис туралы ақпарат",intro:"NIS Hub деректеріңізді қалай өңдейді және сервисті пайдалану ережелері.",
 revision:"Жаңартылған күні: 26.09.2026.",privacyTitle:"Құпиялық саясаты",termsTitle:"Пайдалану шарттары",
 privacy:[
 ["Оператор және байланыс",contact+". Жеке деректер мен жою туралы сұраулар үшін осы email арқылы операторға хабарласыңыз. Құпиясөз, ЖСН, токен немесе қол қойылған сілтемелер жібермеңіз. Сұрауды орындау алдында аккаунттың сізге тиесілі екенін растау қажет болуы мүмкін."],
 ["Аккаунт және профиль","Supabase Auth кіру үшін email, құпиясөз және сессияны өңдейді. Supabase аккаунт идентификаторын, көрсетілетін есімді, сыныпты, Bio, Top 4 пәндерін, рөлді, өзгеріс уақытын және аватар жолын сақтайды. Есім, Bio және Top 4 басқа кірген қатысушыларға көрінеді; email, сынып, оқу тарихы мен өтініштер ашық профильге кірмейді."],
 ["Аватар, бетбелгілер және оқу","Аватар жеке Supabase Storage ішінде <uid>/avatar.webp жолымен сақталады. Сурет бастапқы метадеректерсіз WebP форматына айналады, жаңа жүктеу алдыңғы файлды ауыстырады. Басқа қатысушылар жеке аватардың орнына инициалдарды көреді. Бетбелгі мен соңғы бет пайдаланушыға және оқулық нұсқасына байланыстырылып сақталады. Уақытша қол қойылған сілтемелер рұқсат етілген файлдарға шектеулі уақытқа қолжетімділік береді; оларды таратпаңыз."],
 ["Баптаулар және техникалық деректер","Supabase cookies кіруді және сессияны жаңартуды қамтамасыз етеді. nis-locale cookie тілді бір жылға дейін сақтайды; localStorage ішіндегі nis-theme және nis-sidebar тақырып пен панель күйін өзгертілгенше не тазаланғанша сақтайды. Library сүзгілері URL ішінде және браузер тарихында қалуы мүмкін. NIS Hub кіру диагностикасына тек қауіпсіз қате санаты, коды және күйі жазылады; email, құпиясөз, cookies пен токендер жазылмайды. Хостинг өз техникалық журналдарын жүргізуі мүмкін."],
 ["Хостинг және кесте","Қолданба Vercel-де орналасқан; Supabase Auth, дерекқор және жеке Storage қызметтерін береді. Сервер рұқсат етілген EduPage кестесін алады; әкімшілер оны тексеріп жариялайды, CSV/TSV импорты да бар. Базада кесте нұсқалары, күнтізбе және әкімшілік әрекеттер тарихы сақталады. EduPage үшін SMS құпиясөзі қолданылмайды. PDF.js, қаріптер және пәндік иллюстрациялар сайттан жүктеледі; иллюстрациялар оқулық мұқабалары емес."],
 ["Қосымша SMS күнделігі","Сіздің сұрауыңызбен ЖСН және құпиясөз NIS Hub серверінде уақытша өңделіп, HTTPS арқылы sms.ura.nis.edu.kz мектеп жүйесіне жіберіледі. Олар базаға, браузер қоймасына немесе қолданба журналдарына сақталмайды. SMS cookies AES-256-GCM арқылы шифрланып, аккаунтқа байланады; сессия ең көбі 30 минут немесе SMS мерзімі қысқа болса, одан аз уақыт әрекет етеді. Ол HttpOnly cookie ішінде, ал үлкен шифрланған сессиялар Supabase ішінде TTL арқылы сақталып, cookie тек жабық идентификаторды ұстайды. Ажырату жергілікті сессия мен қолжетімді сервер жазбасын жояды. Бағалар сервер/бет жадында болады, NIS Hub базасына сақталмайды және Gemini не Telegram-ға жіберілмейді."],
 ["Қосымша AI Study","AI іске қосылғанда сервер Google Gemini-ге таңдалған беттердің мәтінін, режим мен тілді ғана жібереді; бүкіл кітапхананы, профильді, email, құпиясөз немесе қол қойылған URL жібермейді. Жауаптарды тексеру кезінде бастапқы сұрақтар мен сіздің жауаптарыңыз да жіберіледі. PDF мәтіні Supabase ішінде беттер бойынша сақталады; генерациялар иесі, кітап нұсқасы, диапазон, дереккөз хэші және жауаппен бірге кэштеледі. Әрекет метадеректері лимиттерді қамтамасыз етеді. Өзін-өзі тексеру жауаптары мен кері байланыс қойынды жадында ғана қалады, NIS Hub оларды сақтамайды және журналға жазбайды. Таңдалған Gemini тарифінің шарттары қолданылады: тегін тариф материалдары қызметтерді жақсарту үшін пайдаланылып, адамдармен қаралуы мүмкін. Құпия мәтінді таңдамаңыз."],
 ["Тапсырмалар, хабарламалар және хабарландырулар","Supabase жеке тапсырмаларды, ескертпелерді, маңыздылықты, мерзімдерді, еске салу уақытын және орындалу күйін сақтайды; оларды тек иесі көреді. Supabase хат алмасу қатысушыларын, мәтіндерді, уақыт пен оқылу белгілерін де сақтайды. Еске салулар NIS Hub ішінде және айқын рұқсаттан кейін сайт ашық тұрғанда браузерде көрсетіледі; сайт толық жабық болғанда фондық push хабарландырулары жоқ."],
 ["Сақтау және жою","Деректер тиісті функцияның жұмысына және пайдаланушы сұрауларын орындауға қажет уақыт бойы сақталады. Жалпы сақтау және сұрауларды өңдеу мерзімдері әзірше бекітілмеген. Профильді түзетуге, бетбелгілерді жоюға және көрсетілген байланыс арқылы аккаунтты/деректерді жоюды сұрауға болады. Аккаунтты өздігінен автоматты жою функциясы жоқ. Оператор аккаунттың тиесілігін, байланысты жазбаларды және Storage файлдарын бөлек тексереді; журналдар, Telegram және резервтік көшірмелер бөлек қаралады. Техникалық журналдар мен резервтік көшірмелер мерзімдері провайдер баптауларына тәуелді; барлық көшірмелерді бірден жоюға уәде берілмейді."],
 ["Аудитория және қауіпсіздік","NIS Hub 18+ кәмелетке толған пайдаланушыларға арналған. Қолданба жасты техникалық түрде тексермейді. Артық жеке немесе өзгенің деректерін енгізбеңіз. Жеке Storage және қолжетімділік ережелері қолданбадағы қолжетімділікті шектейді, бірақ DRM емес және инфрақұрылым әкімшісінің техникалық қолжетімділігін жоққа шығармайды."]
 ],
 terms:[
 ["Мақсаты және оператор","NIS Hub оқу материалдарымен, кестемен және жеке оқу кеңістігімен жұмыс істеуге көмектеседі. Оператор: "+contact+". Бұл дербес сервис; мектептің немесе НЗМ желісінің ресми өкілдігі деп мәлімделмейді."],
 ["Аккаунт","Сервис 18+ пайдаланушыларға арналған. Өз аккаунтыңызды пайдаланыңыз, құпиясөз бен email қолжетімділігін қорғаңыз, сессияны басқаға бермеңіз. Қауіпсіздік бұзылды деп күдіктенсеңіз, құпия деректерді жібермей операторға хабарлаңыз."],
 ["Материалдар","Авторизация тексерілгеннен кейін тек жарияланған рұқсат етілген материалдарға қолжетімділік беріледі. Қолжетімділік авторлық құқықтарды бермейді. Тиісті рұқсатсыз жеке сілтемелерді немесе көшірмелерді жарияламаңыз."],
 ["Кесте және SMS","Кестедегі маңызды өзгерістерді мектептен тексеріңіз. Тек өзіңіздің рұқсат етілген SMS аккаунтыңызды қосыңыз. NIS Hub мектеп сервисінің қолжетімді деректерін көрсетеді; есептелген пайыздар арнайы белгіленеді және ресми қорытынды баға емес. Қолжетімділік мектеп жүйелерінің жұмысына да байланысты."],
 ["AI және шектеулер","AI Study — таңдалған дереккөз бойынша қосымша оқу көмекшісі, ресми емтихан алушы емес. Жауап толық болмауы немесе қате болуы мүмкін: дереккөз бен дәйексөздерді тексеріңіз. Диапазон мен сұрау жиілігі шектеледі; қолжетімділік провайдерге байланысты. Құпия материалдарды жібермеңіз."],
 ["Қолжетімділік және өтініштер","Ақаулар не техникалық қызмет кезінде сервис қолжетімсіз болуы мүмкін. Әкімшілер қолданыстағы модерация құралдарымен теріс пайдалануды шектей алады. Деректер және жою мәселелері бойынша "+serviceOperator.email+" мекенжайына хабарласыңыз. Нақты жауап мерзімі белгіленбеген; өтінішке құпиясөз не токен қоспаңыз."]
 ]},
 en:{
 label:"Service information",intro:"How NIS Hub handles your data and the rules for using the service.",
 revision:"Updated: 26 September 2026.",privacyTitle:"Privacy Policy",termsTitle:"Terms of Use",
 privacy:[
 ["Operator and contact",contact+". Contact the operator at this email about personal data or deletion. Do not send passwords, IINs, tokens or signed links. Account ownership may need to be verified before a request can be carried out."],
 ["Account and profile","Supabase Auth processes your email, password and session for sign-in. Supabase stores your account ID, display name, class, Bio, Top 4 subjects, role, update timestamps and avatar path. Other signed-in members can see your name, Bio and Top 4; email, class, reading history and support tickets are not part of your public profile."],
 ["Avatar, bookmarks and reading","Avatars are held in private Supabase Storage at <uid>/avatar.webp. Images are converted to WebP without original metadata, and a new upload replaces the previous file. Other members see initials rather than your private avatar. Bookmarks and the last page are saved per user and textbook edition. Temporary signed links provide time-limited access to authorized files; do not share them."],
 ["Preferences and technical data","Supabase cookies maintain sign-in and session refresh. The nis-locale cookie stores language for up to one year; localStorage nis-theme and nis-sidebar retain theme and sidebar preferences until changed or cleared. Library filters appear in URLs and may remain in browser history. NIS Hub sign-in diagnostics record only a safe error category, code and status, never email, passwords, cookies or tokens. The hosting provider may maintain its own technical logs."],
 ["Hosting and timetable","Vercel hosts the application; Supabase provides Auth, the database and private Storage. The server retrieves authorized EduPage timetables; administrators review and publish them, with CSV/TSV import also available. Timetable versions, calendar entries and administrative history remain in the database. Your SMS password is not used for EduPage. PDF.js, fonts and subject illustrations load from this site; the illustrations are not textbook covers."],
 ["Optional SMS Diary","At your request, your IIN and password are handled transiently by the NIS Hub server and sent over HTTPS to the school system sms.ura.nis.edu.kz. They are not saved in the database, browser storage or application logs. SMS cookies are AES-256-GCM encrypted and bound to your account for at most 30 minutes or the shorter SMS lifetime. They are held in an HttpOnly cookie; larger encrypted sessions use Supabase TTL storage with an opaque cookie identifier. Disconnect removes the local session and available server record. Grades remain in server/page memory, are not stored in the NIS Hub database and are not sent to Gemini or Telegram."],
 ["Optional AI Study","When you start AI Study, the server sends Google Gemini the selected page text, mode and language, not the entire library, profile, email, password or signed URLs. Answer review also sends the original questions and your answers. PDF text is extracted into Supabase by page; generations are cached with owner, edition, range, source hash and response. Attempt metadata supports usage limits. Self-check answers and feedback stay in tab memory and are not persisted or logged by NIS Hub. The configured Gemini plan's terms apply: free-tier material may be used to improve services and reviewed by people. Do not select confidential text."],
 ["Tasks, messages and notifications","Supabase stores personal tasks, notes, priorities, deadlines, reminder times and completion state; only the owner can access them. Supabase also stores conversation participants, messages, timestamps and read markers. Participants can access their conversations; there is no end-to-end encryption. Reminders appear in NIS Hub and, after explicit permission, in the browser while the site remains open; background push notifications are not sent when the site is fully closed."],
 ["Retention and deletion","Data is kept as long as necessary to operate the relevant feature and fulfil user requests. Fixed general retention and request-handling periods have not yet been approved. You can edit your profile, remove bookmarks and request account/data deletion using the contact above. Automated self-service account deletion is not available. The operator verifies ownership, dependent records and Storage files separately; logs, Telegram and backups require separate review. Technical-log and backup retention depends on current provider settings; immediate erasure of every copy is not promised."],
 ["Audience and security","NIS Hub is intended for adults aged 18+. The application does not technically verify age. Do not enter unnecessary personal information or other people's data. Private Storage and access rules restrict in-app access but are not DRM and do not exclude technical access by infrastructure administrators."]
 ],
 terms:[
 ["Purpose and operator","NIS Hub helps you use learning materials, timetables and your personal study workspace. Operator: "+contact+". It is an independent service; official representation of the school or NIS network is not claimed."],
 ["Account","The service is intended for adults aged 18+. Use your own account, protect your password and email access, and do not share your session. Report suspected compromise to the operator without sending secrets."],
 ["Materials","Only published, authorized materials are available after authorization checks. Access does not transfer copyright. Do not publish private links or copies without the appropriate permission."],
 ["Timetable and SMS","Confirm important timetable changes with the school. Connect only your own authorized SMS account. NIS Hub displays available school-service data; locally calculated percentages are explicitly labelled and are not official final grades. Availability also depends on school systems."],
 ["AI and limits","AI Study is an optional learning aid grounded in the selected source, not an official examiner. Responses can be incomplete or wrong: verify sources and quotations. Selection and request-frequency limits apply; availability depends on the provider. Do not send confidential material."],
 ["Availability and requests","The service may be unavailable during outages or maintenance. Administrators can restrict abuse using existing moderation tools. Contact "+serviceOperator.email+" about data or deletion. No fixed response deadline is set; never include passwords or tokens in a ticket."]
 ]}
};
for(const locale of ["ru","kk","en"] as const) {
 legalCopy[locale].privacy.push(supportLegalCopy[locale].privacy,v053Legal[locale].privacy);
 legalCopy[locale].terms.push(supportLegalCopy[locale].terms,v053Legal[locale].terms);
}
