import type {Locale} from "./i18n";

const copy={
 ru:{
  title:"Задачи",subtitle:"Личный план без лишнего шума",add:"Новая задача",edit:"Изменить задачу",save:"Сохранить задачу",saving:"Сохраняем…",cancel:"Отмена",
  taskTitle:"Что нужно сделать",taskTitlePlaceholder:"Например, повторить механику",notes:"Заметка",notesPlaceholder:"Материалы, шаги или полезная ссылка",subject:"Предмет",noSubject:"Без предмета",priority:"Важность",due:"Срок",noDue:"Без срока",reminder:"Напомнить",customReminder:"Свое время",reminderTime:"Время напоминания",
  low:"Низкая",medium:"Обычная",high:"Важная",urgent:"Срочная",active:"В работе",today:"Сегодня",upcoming:"Дальше",completed:"Готово",all:"Все",
  empty:"Здесь спокойно",emptyHint:"Добавьте первую задачу — она появится и на главной.",emptyFiltered:"В этом разделе задач нет.",overdue:"Просрочено",dueToday:"Сегодня",tomorrow:"Завтра",done:"Выполнить",undo:"Вернуть",editAction:"Изменить",archive:"В архив",archived:"Задача убрана в архив.",saved:"Задача сохранена.",completedMessage:"Готово. Отличная работа.",restored:"Задача снова в работе.",failed:"Не удалось обновить задачи. Проверьте подключение и миграцию.",unavailable:"Задача уже изменена или недоступна.",invalid:"Проверьте название, срок и время напоминания.",migration:"Примените миграцию задач Supabase.",rate:"Слишком много изменений. Попробуйте позже.",limit:"Достигнут лимит активных задач.",
  remindNone:"Не напоминать",remindAtDue:"В момент срока",remind10:"За 10 минут",remind30:"За 30 минут",remind60:"За 1 час",remind180:"За 3 часа",remindDay:"За день",remindCustom:"Выбрать время",browserTitle:"Уведомления браузера",browserHint:"Показывать напоминания, пока NIS Hub открыт.",enableBrowser:"Включить",disableBrowser:"Выключить",browserOn:"Включены",browserDenied:"Уведомления заблокированы в настройках браузера.",browserUnsupported:"Этот браузер не поддерживает системные уведомления.",
  manage:"Все задачи",progress:"выполнено",remaining:"осталось",snooze:"Отложить на 10 минут",reminderLabel:"Напоминание о задаче",noDeadline:"Срок не задан",quickHint:"Ближайшие задачи и важные дедлайны",openProfile:"Управлять в профиле",close:"Закрыть",optional:"Необязательно",
 },
 kk:{
  title:"Тапсырмалар",subtitle:"Артық шуылсыз жеке жоспар",add:"Жаңа тапсырма",edit:"Тапсырманы өзгерту",save:"Тапсырманы сақтау",saving:"Сақталуда…",cancel:"Бас тарту",
  taskTitle:"Не істеу керек",taskTitlePlaceholder:"Мысалы, механиканы қайталау",notes:"Ескертпе",notesPlaceholder:"Материалдар, қадамдар немесе сілтеме",subject:"Пән",noSubject:"Пәнсіз",priority:"Маңыздылығы",due:"Мерзімі",noDue:"Мерзімсіз",reminder:"Еске салу",customReminder:"Өз уақыты",reminderTime:"Еске салу уақыты",
  low:"Төмен",medium:"Қалыпты",high:"Маңызды",urgent:"Шұғыл",active:"Орындалуда",today:"Бүгін",upcoming:"Кейін",completed:"Дайын",all:"Барлығы",
  empty:"Әзірше тыныш",emptyHint:"Алғашқы тапсырманы қосыңыз — ол басты бетте де көрінеді.",emptyFiltered:"Бұл бөлімде тапсырма жоқ.",overdue:"Мерзімі өтті",dueToday:"Бүгін",tomorrow:"Ертең",done:"Орындау",undo:"Қайтару",editAction:"Өзгерту",archive:"Мұрағатқа",archived:"Тапсырма мұрағатқа жіберілді.",saved:"Тапсырма сақталды.",completedMessage:"Дайын. Жарайсың!",restored:"Тапсырма қайта жұмысқа қосылды.",failed:"Тапсырмаларды жаңарту мүмкін болмады. Қосылым мен миграцияны тексеріңіз.",unavailable:"Тапсырма бұрын өзгертілген немесе қолжетімсіз.",invalid:"Атауын, мерзімін және еске салу уақытын тексеріңіз.",migration:"Supabase тапсырмалар миграциясын қолданыңыз.",rate:"Өзгеріс тым көп. Кейінірек қайталаңыз.",limit:"Белсенді тапсырмалар шегіне жеттіңіз.",
  remindNone:"Еске салмау",remindAtDue:"Мерзім кезінде",remind10:"10 минут бұрын",remind30:"30 минут бұрын",remind60:"1 сағат бұрын",remind180:"3 сағат бұрын",remindDay:"Бір күн бұрын",remindCustom:"Уақытты таңдау",browserTitle:"Браузер хабарландырулары",browserHint:"NIS Hub ашық кезде еске салуларды көрсету.",enableBrowser:"Қосу",disableBrowser:"Өшіру",browserOn:"Қосулы",browserDenied:"Хабарландырулар браузер баптауларында бұғатталған.",browserUnsupported:"Бұл браузер жүйелік хабарландыруларды қолдамайды.",
  manage:"Барлық тапсырма",progress:"орындалды",remaining:"қалды",snooze:"10 минутқа шегеру",reminderLabel:"Тапсырма еске салуы",noDeadline:"Мерзім қойылмаған",quickHint:"Жақын тапсырмалар мен маңызды мерзімдер",openProfile:"Профильде басқару",close:"Жабу",optional:"Міндетті емес",
 },
 en:{
  title:"Tasks",subtitle:"A personal plan without the noise",add:"New task",edit:"Edit task",save:"Save task",saving:"Saving…",cancel:"Cancel",
  taskTitle:"What needs doing",taskTitlePlaceholder:"For example, review mechanics",notes:"Note",notesPlaceholder:"Materials, steps, or a useful link",subject:"Subject",noSubject:"No subject",priority:"Priority",due:"Deadline",noDue:"No deadline",reminder:"Remind me",customReminder:"Custom time",reminderTime:"Reminder time",
  low:"Low",medium:"Normal",high:"Important",urgent:"Urgent",active:"In progress",today:"Today",upcoming:"Later",completed:"Done",all:"All",
  empty:"All clear",emptyHint:"Add your first task and it will also appear on Home.",emptyFiltered:"There are no tasks in this section.",overdue:"Overdue",dueToday:"Today",tomorrow:"Tomorrow",done:"Complete",undo:"Restore",editAction:"Edit",archive:"Archive",archived:"Task moved to the archive.",saved:"Task saved.",completedMessage:"Done. Nice work.",restored:"Task is active again.",failed:"Could not update tasks. Check the connection and migration.",unavailable:"This task has already changed or is unavailable.",invalid:"Check the title, deadline, and reminder time.",migration:"Apply the Supabase tasks migration.",rate:"Too many changes. Try again later.",limit:"You have reached the active task limit.",
  remindNone:"No reminder",remindAtDue:"At the deadline",remind10:"10 minutes before",remind30:"30 minutes before",remind60:"1 hour before",remind180:"3 hours before",remindDay:"1 day before",remindCustom:"Choose a time",browserTitle:"Browser notifications",browserHint:"Show reminders while NIS Hub is open.",enableBrowser:"Enable",disableBrowser:"Disable",browserOn:"Enabled",browserDenied:"Notifications are blocked in your browser settings.",browserUnsupported:"This browser does not support system notifications.",
  manage:"All tasks",progress:"completed",remaining:"remaining",snooze:"Snooze for 10 minutes",reminderLabel:"Task reminder",noDeadline:"No deadline",quickHint:"Upcoming tasks and important deadlines",openProfile:"Manage in profile",close:"Close",optional:"Optional",
 },
} as const;

export const tasksCopy=(locale:Locale)=>copy[locale];
export type TasksCopy=ReturnType<typeof tasksCopy>;
