import type { Locale } from "./i18n";
const copy = {
  ru: {
    materialsShort: "Материалы",
    lessonActions: "Действия с уроком",
    addHomework: "Добавить Д/З",
    homeworkSaved: "Д/З добавлено",
    homeworkPlaceholder: "Например, стр. 42, упражнения 3–5",
    saving: "Сохраняем…",
    viewProfile: "Открыть профиль",
    backMessages: "К сообщениям",
    favoriteSubjects: "Любимые предметы",
    searchEmpty: "Найдите знакомых из NIS Hub",
    searchEmptyHint:
      "Введите имя ученика, чтобы открыть профиль или начать переписку.",
    friendsEmpty: "Друзей пока нет",
    friendsEmptyHint: "Найдите знакомого ученика и отправьте заявку в друзья.",
    requestsEmpty: "Новых заявок нет",
    requestsEmptyHint: "Здесь появятся ваши заявки и приглашения в друзья.",
    blockedEmpty: "Список заблокированных пуст",
    blockedEmptyHint: "Здесь можно будет разблокировать ученика.",
    noResultsHint: "Попробуйте другое имя или проверьте написание.",

    people: "Ученики",
    friends: "Друзья",
    requests: "Заявки",
    blocked: "Заблокированные",
    search: "Найти ученика",
    searchHint: "Имя, минимум 2 символа. Показаны только участники NIS Hub.",
    bio: "О себе",
    bioHint:
      "До 280 символов. Имя, Bio и Top 4 видны вошедшим участникам. Не указывайте личные контакты.",
    none: "Ничего не найдено",
    unavailable: "Профиль недоступен",
    failed: "Не удалось выполнить действие. Повторите позже.",
    rate: "Слишком много действий. Повторите позже.",
    migration: "Требуется миграция v0.5.3. Обратитесь к администратору.",
    request: "Добавить в друзья",
    accept: "Принять",
    remove: "Удалить / отклонить",
    outgoing: "Заявка отправлена",
    incoming: "Входящая заявка",
    friend: "В друзьях",
    self: "Ваш профиль",
    message: "Написать",
    more: "Далее",
    previous: "Назад",
    safety: "Действия и безопасность",
    block: "Заблокировать",
    unblock: "Разблокировать",
    hide: "Скрыть диалог у меня",
    hideHint:
      "Новые сообщения не возвращают скрытый диалог. Откройте его заново через профиль или имя.",
    deleteOwn: "Удалить моё сообщение",
    deleted: "Сообщение удалено",
    report: "Пожаловаться",
    reason: "Причина",
    spam: "Спам",
    harassment: "Оскорбления / травля",
    privacy: "Личные данные",
    other: "Другое",
    details: "Описание (до 500 символов)",
    sent: "Готово",
    homework: "Домашнее задание класса",
    homeworkHint:
      "Записи участников, не проверены учителем. Видны только вашему текущему классу.",
    due: "На дату",
    body: "Задание (до 1000 символов)",
    save: "Сохранить",
    edit: "Изменить",
    cancel: "Отмена",
    delete: "Удалить",
    adminHide: "Скрыть запись",
    materials: "Открыть материалы",
    moderation: "Жалобы сообщества",
    resolve: "Закрыть жалобу",
    reviewAnswers: "Проверить ответы по учебнику",
    answer: "Ваш ответ",
    reviewHint:
      "Проверка использует те же страницы и расходует один AI-запрос. Ответы отправляются Gemini, не сохраняются в NIS Hub. Это учебная обратная связь, не официальная оценка.",
    correct: "Верно",
    partial: "Частично",
    incorrect: "Неверно",
    insufficient: "Недостаточно источника",
    topics: "Повторить",
    community: "Сообщество",
  },
  kk: {
    materialsShort: "Материалдар",
    lessonActions: "Сабақ әрекеттері",
    addHomework: "Үй тапсырмасын қосу",
    homeworkSaved: "Тапсырма қосылды",
    homeworkPlaceholder: "Мысалы, 42-бет, 3–5-жаттығулар",
    saving: "Сақталуда…",
    viewProfile: "Профильді ашу",
    backMessages: "Хабарламаларға",
    favoriteSubjects: "Сүйікті пәндер",
    searchEmpty: "NIS Hub-та таныстарыңызды табыңыз",
    searchEmptyHint:
      "Профильді ашу немесе хат жазу үшін оқушының есімін енгізіңіз.",
    friendsEmpty: "Әзірге достар жоқ",
    friendsEmptyHint: "Таныс оқушыны тауып, достық өтінімін жіберіңіз.",
    requestsEmpty: "Жаңа өтінімдер жоқ",
    requestsEmptyHint: "Достық өтінімдері мен шақырулар осында көрінеді.",
    blockedEmpty: "Бұғатталған оқушылар жоқ",
    blockedEmptyHint: "Оқушыны осы жерден бұғаттан шығаруға болады.",
    noResultsHint: "Басқа есімді енгізіңіз немесе жазылуын тексеріңіз.",

    people: "Оқушылар",
    friends: "Достар",
    requests: "Өтінімдер",
    blocked: "Бұғатталғандар",
    search: "Оқушыны табу",
    searchHint: "Есім, кемінде 2 таңба. Тек NIS Hub қатысушылары көрсетіледі.",
    bio: "Өзім туралы",
    bioHint:
      "280 таңбаға дейін. Есім, Bio және Top 4 кірген қатысушыларға көрінеді. Жеке байланыс деректерін жазбаңыз.",
    none: "Ештеңе табылмады",
    unavailable: "Профиль қолжетімсіз",
    failed: "Әрекет орындалмады. Кейінірек қайталаңыз.",
    rate: "Әрекет тым көп. Кейінірек қайталаңыз.",
    migration: "v0.5.3 миграциясы қажет. Әкімшіге хабарласыңыз.",
    request: "Досқа қосу",
    accept: "Қабылдау",
    remove: "Жою / қабылдамау",
    outgoing: "Өтінім жіберілді",
    incoming: "Кіріс өтінім",
    friend: "Достар қатарында",
    self: "Сіздің профиліңіз",
    message: "Хабарлама жазу",
    more: "Келесі",
    previous: "Артқа",
    safety: "Әрекеттер және қауіпсіздік",
    block: "Бұғаттау",
    unblock: "Бұғаттан шығару",
    hide: "Диалогты өзімде жасыру",
    hideHint:
      "Жаңа хабарламалар жасырылған диалогты қайтармайды. Профиль немесе есім арқылы қайта ашыңыз.",
    deleteOwn: "Өз хабарламамды жою",
    deleted: "Хабарлама жойылды",
    report: "Шағымдану",
    reason: "Себеп",
    spam: "Спам",
    harassment: "Қорлау / қудалау",
    privacy: "Жеке деректер",
    other: "Басқа",
    details: "Сипаттама (500 таңбаға дейін)",
    sent: "Дайын",
    homework: "Сыныптың үй тапсырмасы",
    homeworkHint:
      "Қатысушылардың жазбалары, мұғалім тексермеген. Тек қазіргі сыныбыңызға көрінеді.",
    due: "Күніне",
    body: "Тапсырма (1000 таңбаға дейін)",
    save: "Сақтау",
    edit: "Өзгерту",
    cancel: "Болдырмау",
    delete: "Жою",
    adminHide: "Жазбаны жасыру",
    materials: "Материалдарды ашу",
    moderation: "Қауымдастық шағымдары",
    resolve: "Шағымды жабу",
    reviewAnswers: "Жауаптарды оқулық бойынша тексеру",
    answer: "Сіздің жауабыңыз",
    reviewHint:
      "Тексеру сол беттерді пайдаланады және бір AI сұрауын жұмсайды. Жауаптар Gemini-ге жіберіледі, NIS Hub-та сақталмайды. Бұл ресми баға емес, оқу кері байланысы.",
    correct: "Дұрыс",
    partial: "Ішінара",
    incorrect: "Қате",
    insufficient: "Дереккөз жеткіліксіз",
    topics: "Қайталау",
    community: "Қауымдастық",
  },
  en: {
    materialsShort: "Materials",
    lessonActions: "Lesson actions",
    addHomework: "Add homework",
    homeworkSaved: "Homework added",
    homeworkPlaceholder: "For example, page 42, exercises 3–5",
    saving: "Saving…",
    viewProfile: "View profile",
    backMessages: "Back to messages",
    favoriteSubjects: "Favorite subjects",
    searchEmpty: "Find your classmates on NIS Hub",
    searchEmptyHint:
      "Enter a student’s name to view their profile or start a conversation.",
    friendsEmpty: "No friends yet",
    friendsEmptyHint: "Find a classmate and send them a friend request.",
    requestsEmpty: "No new requests",
    requestsEmptyHint: "Your friend requests and invitations will appear here.",
    blockedEmpty: "No blocked students",
    blockedEmptyHint: "You can unblock students here.",
    noResultsHint: "Try another name or check the spelling.",

    people: "Students",
    friends: "Friends",
    requests: "Requests",
    blocked: "Blocked",
    search: "Find a student",
    searchHint: "Display name, at least 2 characters. NIS Hub members only.",
    bio: "Bio",
    bioHint:
      "Up to 280 characters. Your name, Bio and Top 4 are visible to signed-in members. Do not include private contact details.",
    none: "No results",
    unavailable: "Profile unavailable",
    failed: "Could not complete the action. Try again.",
    rate: "Too many actions. Try again later.",
    migration: "The v0.5.3 migration is required. Contact an administrator.",
    request: "Add friend",
    accept: "Accept",
    remove: "Remove / decline",
    outgoing: "Request sent",
    incoming: "Incoming request",
    friend: "Friends",
    self: "Your profile",
    message: "Message",
    more: "Next",
    previous: "Previous",
    safety: "Actions and safety",
    block: "Block",
    unblock: "Unblock",
    hide: "Hide for me",
    hideHint:
      "New messages do not unhide a conversation. Reopen it from the profile or by name.",
    deleteOwn: "Delete my message",
    deleted: "Message deleted",
    report: "Report",
    reason: "Reason",
    spam: "Spam",
    harassment: "Harassment",
    privacy: "Private information",
    other: "Other",
    details: "Details (up to 500 characters)",
    sent: "Done",
    homework: "Class homework",
    homeworkHint:
      "Student contributions, not teacher verified. Visible only to your current class.",
    due: "Due date",
    body: "Assignment (up to 1000 characters)",
    save: "Save",
    edit: "Edit",
    cancel: "Cancel",
    delete: "Delete",
    adminHide: "Hide contribution",
    materials: "Open materials",
    moderation: "Community reports",
    resolve: "Close report",
    reviewAnswers: "Check answers against the textbook",
    answer: "Your answer",
    reviewHint:
      "Review uses the same pages and consumes one AI request. Answers are sent to Gemini, not stored in NIS Hub. This is practice feedback, not an official grade.",
    correct: "Correct",
    partial: "Partially correct",
    incorrect: "Incorrect",
    insufficient: "Insufficient source",
    topics: "Topics to review",
    community: "Community",
  },
};
export const v053Copy = (locale: Locale) => copy[locale];
