import type { Locale } from "./i18n";

const copy = {
  ru: {
    space: "Учебное пространство",
    title: "Всё для учёбы.",
    titleAccent: "На одной странице.",
    description: "Расписание, учебники и ваши закладки — собраны в NIS Hub.",
    greeting: "С возвращением",
    hello: "Здравствуйте",
    todayHint: "Ваши занятия на сегодня",
    readingHint: "Недавно открытые учебники",
    class: "Класс",
    desk: "Ваш учебный стол",
    deskHint: "Планы на сегодня и книги, которые вы читаете.",
    savedHint: "Сохранённые страницы и избранные предметы — в вашем профиле.",
    routes: "От урока",
    routesAccent: "к новой странице.",
    routeHint: "Найдите нужный учебник, сверьтесь с расписанием или вернитесь к сохранённому.",
    library: "Библиотека",
    libraryHint: "Учебники по предметам и классам. Откройте книгу и читайте с того места, где остановились.",
    schedule: "Расписание",
    scheduleHint: "Предметы, время занятий и кабинеты. Ваш учебный день — перед глазами.",
    profile: "Личное пространство",
    profileHint: "Избранные предметы, сохранённые страницы и настройки вашего класса.",
    openLibrary: "Открыть библиотеку",
    openSchedule: "Посмотреть расписание",
    openProfile: "Перейти в профиль",
    closing: "Следующая глава —",
    closingAccent: "в библиотеке.",
    closingHint: "Выберите предмет. Найдите книгу. Продолжайте читать.",
    pause: "Остановить анимацию",
    resume: "Включить анимацию",
  },
  kk: {
    space: "Оқу кеңістігі",
    title: "Оқуға қажеттінің бәрі.",
    titleAccent: "Бір бетте.",
    description: "Сабақ кестесі, оқулықтар мен бетбелгілеріңіз — NIS Hub-та.",
    greeting: "Қайта қош келдіңіз",
    hello: "Сәлем",
    todayHint: "Бүгінгі сабақтарыңыз",
    readingHint: "Жақында ашылған оқулықтар",
    class: "Сынып",
    desk: "Сіздің оқу үстеліңіз",
    deskHint: "Бүгінгі жоспарлар мен оқып жүрген кітаптарыңыз.",
    savedHint: "Сақталған беттер мен таңдаулы пәндер — профиліңізде.",
    routes: "Сабақтан",
    routesAccent: "жаңа бетке.",
    routeHint: "Қажетті оқулықты табыңыз, кестені қараңыз немесе сақталған бетке оралыңыз.",
    library: "Кітапхана",
    libraryHint: "Пәндер мен сыныптар бойынша оқулықтар. Кітапты ашып, тоқтаған жеріңізден оқыңыз.",
    schedule: "Сабақ кестесі",
    scheduleHint: "Пәндер, сабақ уақыты және кабинеттер. Оқу күніңіз — көз алдыңызда.",
    profile: "Жеке кеңістік",
    profileHint: "Таңдаулы пәндер, сақталған беттер және сынып баптаулары.",
    openLibrary: "Кітапхананы ашу",
    openSchedule: "Сабақ кестесін қарау",
    openProfile: "Профильге өту",
    closing: "Келесі тарау —",
    closingAccent: "кітапханада.",
    closingHint: "Пәнді таңдаңыз. Кітапты табыңыз. Оқуды жалғастырыңыз.",
    pause: "Анимацияны тоқтату",
    resume: "Анимацияны қосу",
  },
  en: {
    space: "Your learning space",
    title: "A school day.",
    titleAccent: "All on one page.",
    description: "Your timetable, textbooks and bookmarks, together in NIS Hub.",
    greeting: "Welcome back",
    hello: "Hello",
    todayHint: "Your lessons for today",
    readingHint: "Recently opened textbooks",
    class: "Class",
    desk: "Your study desk",
    deskHint: "Today's plans and the books you are reading.",
    savedHint: "Your saved pages and favourite subjects are in your profile.",
    routes: "From a lesson",
    routesAccent: "to a new page.",
    routeHint: "Find a textbook, check your timetable or return to a saved page.",
    library: "Library",
    libraryHint: "Textbooks by subject and grade. Open a book and pick up where you left off.",
    schedule: "Timetable",
    scheduleHint: "Subjects, lesson times and rooms. Your school day at a glance.",
    profile: "Personal space",
    profileHint: "Favourite subjects, saved pages and your class settings.",
    openLibrary: "Explore the library",
    openSchedule: "View timetable",
    openProfile: "Open profile",
    closing: "The next chapter",
    closingAccent: "is in the library.",
    closingHint: "Choose a subject. Find a book. Keep reading.",
    pause: "Pause animation",
    resume: "Enable animation",
  },
};

export function vintageCopy(locale: Locale) { return copy[locale]; }
