import test from "node:test";
import assert from "node:assert/strict";
import { v051Database } from "./helpers/v051-database";
import { asUser,fixtureId as id } from "./helpers/database";
import { messagePreview } from "../src/lib/people";
import { materialDestinations,materialKey } from "../src/lib/schedule-materials";
import { v053Copy } from "../src/lib/v053-copy";
import { profileSchema } from "../src/lib/validation";
test("v053 Unicode preview, complete locales, Bio bounds and deterministic material destinations",()=>{
 const preview=messagePreview("🧑".repeat(121));assert.equal(Array.from(preview).length,120);assert.ok(preview.endsWith("…"));assert.equal(messagePreview("<script>hello</script>"),"<script>hello</script>");
 for(const locale of ["ru","kk","en"]as const){assert.deepEqual(Object.keys(v053Copy(locale)),Object.keys(v053Copy("en")));assert.ok(Object.values(v053Copy(locale)).every(s=>s.length));}
 assert.equal(profileSchema.safeParse({display_name:"Student",class_id:"",subjects:[],bio:"x".repeat(281)}).success,false);
 const books=[{id:id(30),title:"Physics",subject_id:id(20),grade:9}],editions=[{id:id(31),book_id:id(30)},{id:id(32),book_id:id(30)}];
 const key=materialKey(id(20),9);
 assert.equal(materialDestinations(books,editions,[],[id(20)],[9])[key],"/books/"+id(30));
 assert.equal(materialDestinations(books,editions,[id(32)],[id(20)],[9])[key],"/books/"+id(30)+"/read?variant="+id(32));
 assert.equal(materialDestinations(books,[editions[0]],[],[id(20)],[9])[key],"/books/"+id(30)+"/read?variant="+id(31));
 for(const rows of [[],[...books,{...books[0],id:id(40)}]])assert.equal(materialDestinations(rows,editions,[],[id(20)],[9])[key],"/library?subject="+id(20)+"&grade=9");
 assert.ok(materialDestinations(books,editions,[],[id(20)],[9],true)[key].startsWith("/library"));
});
test("v053 actual SQL: safe profiles, friendship states, bilateral blocks, per-user hide, tombstones, reports and own-class homework",async()=>{
 const db=await v051Database();
 try{
 await db.exec(`insert into auth.users(id) values('${id(1)}'),('${id(2)}'),('${id(3)}'),('${id(4)}');
 update profiles set display_name='Student-'||right(id::text,1),bio='Public bio';
 update profiles set role='admin' where id='${id(4)}';
 insert into classes(id,name,grade) values('${id(10)}','9A',9),('${id(11)}','9B',9);
 insert into subjects(id,name,name_ru,name_kz,name_en) values('${id(20)}','Physics','Физика','Физика','Physics');
 update profiles set class_id='${id(10)}' where id in('${id(1)}','${id(2)}');
 update profiles set class_id='${id(11)}' where id='${id(3)}';`);
 await asUser(db,id(1));
 await db.query("select save_profile_v053('Student-1',$1,$2,'Bio update')",[id(10),[id(20)]]);
 await assert.rejects(db.query("select save_profile_v053('Changed',$1,$2,$3)",[id(10),[], "x".repeat(281)]));
 assert.equal((await db.query("select * from profiles")).rows.length,1);
 const profile=(await db.query<Record<string,unknown>>("select * from people_list('profile','',$1)",[id(1)])).rows[0];
 assert.deepEqual(Object.keys(profile),["id","display_name","bio","top_subjects","relationship"]);assert.equal(profile.bio,"Bio update");assert.deepEqual(profile.top_subjects,[id(20)]);
 assert.equal((await db.query("select * from people_list('search','s')")).rows.length,0);
 assert.equal((await db.query("select * from people_list('search','STUDENT')")).rows.length,3);
 assert.equal((await db.query("select * from people_list('search','%_')")).rows.length,0);
 await db.query("select friend_action($1,'request')",[id(2)]);
 await assert.rejects(db.query("select friend_action($1,'accept')",[id(2)]));
 assert.equal((await db.query("select * from dm_threads")).rows.length,0,"friend request never creates chat");
 await asUser(db,id(2));await db.query("select friend_action($1,'accept')",[id(1)]);
 assert.equal((await db.query("select * from people_list('friends')")).rows.length,1);
 await asUser(db,id(3));assert.equal((await db.query("select * from friendships")).rows.length,0);
 await assert.rejects(db.query("insert into friendships(user_a,user_b,requested_by) values($1,$2,$1)",[id(1),id(2)]));
 await asUser(db,id(1));
 const thread=(await db.query<{id:string}>("select start_dm('Student-2') id")).rows[0].id;
 const msg=(await db.query<{id:string}>("select send_dm($1,$2,$3) id",[thread,"🧑".repeat(125),id(40)])).rows[0].id;
 await asUser(db,id(2));
 const notice=(await db.query<{body_preview:string}>("select * from notification_feed_v053()")).rows[0];
 assert.equal(Array.from(notice.body_preview).length,120);assert.ok(notice.body_preview.endsWith("…"));
 assert.equal((await db.query<{peer_id:string}>("select * from dm_inbox_v053()")).rows[0].peer_id,id(1));
 await assert.rejects(db.query("select delete_own_dm($1)",[msg]));
 await db.query("select set_dm_hidden($1,true)",[thread]);
 assert.equal((await db.query("select * from dm_inbox_v053()")).rows.length,0);
 assert.equal((await db.query("select * from notification_feed_v053()")).rows.length,0);
 await asUser(db,id(1));await db.query("select send_dm($1,'Does not unhide',$2)",[thread,id(41)]);
 assert.equal((await db.query("select * from dm_inbox_v053()")).rows.length,1);
 await asUser(db,id(2));assert.equal((await db.query("select * from dm_inbox_v053()")).rows.length,0);
 await db.query("select start_dm('Student-1')");assert.equal((await db.query("select * from dm_inbox_v053()")).rows.length,1);
 const report=(await db.query<{id:string}>("select report_community('message',$1,'harassment','Review this') id",[msg])).rows[0].id;
 assert.equal((await db.query("select * from community_reports")).rows.length,0);
 await assert.rejects(db.query("select community_report_context($1)",[report]));
 await db.query("select set_user_block($1,true)",[id(1)]);
 for(const [uid,peer]of [[id(1),id(2)],[id(2),id(1)]]){
 await asUser(db,uid);
 await assert.rejects(db.query("select send_dm($1,'blocked',$2)",[thread,id(42)]),/unavailable/);
 await assert.rejects(db.query("select start_dm($1)",["Student-"+Number(peer.slice(-1))]),/unavailable/);
 await assert.rejects(db.query("select friend_action($1,'request')",[peer]),/unavailable/);
 assert.equal((await db.query("select * from people_list('profile','',$1)",[peer])).rows.length,0);
 assert.equal((await db.query("select * from friendships")).rows.length,0);
 assert.equal((await db.query("select * from dm_history_v053($1)",[thread])).rows.length,2);
 }
 await asUser(db,id(1));await db.query("select delete_own_dm($1)",[msg]);
 await asUser(db,id(2));
 assert.equal((await db.query("select * from direct_messages where id=$1",[msg])).rows.length,0,"raw table does not expose deleted body");
 const history=await db.query<{id:string;body:string;deleted_at:string|null}>("select * from dm_history_v053($1)",[thread]);
 assert.equal(history.rows.find(m=>m.id===msg)?.body,"");assert.ok(history.rows.find(m=>m.id===msg)?.deleted_at);
 await db.query("select set_user_block($1,false)",[id(1)]);await db.query("select send_dm($1,'unblocked',$2)",[thread,id(43)]);
 await asUser(db,id(3));await assert.rejects(db.query("select dm_history_v053($1)",[thread]));
 await assert.rejects(db.query("select set_dm_hidden($1,true)",[thread]));
 await assert.rejects(db.query("select report_community('message',$1,'other','')",[msg]));
 await asUser(db,id(4));assert.equal((await db.query<{body:string}>("select community_report_context($1) body",[report])).rows[0].body,"🧑".repeat(125));
 await db.query("select resolve_community_report($1)",[report]);
 await asUser(db,id(1));
 const hw=(await db.query<{id:string}>("select save_class_homework($1,current_date,'First contribution') id",[id(20)])).rows[0].id;
 await asUser(db,id(2));const other=(await db.query<{id:string}>("select save_class_homework($1,current_date,'Second contribution') id",[id(20)])).rows[0].id;
 assert.equal((await db.query("select * from class_homework")).rows.length,2);
 await assert.rejects(db.query("select save_class_homework($1,current_date,'Hijack',$2)",[id(20),hw]));
 await assert.rejects(db.query("select delete_class_homework($1)",[hw]));
 await assert.rejects(db.query("update class_homework set body='Bypass'"));
 await assert.rejects(db.query("insert into class_homework(class_id,subject_id,due_date,body,created_by) values($1,$2,current_date,'Spoof',$3)",[id(11),id(20),id(2)]));
 await db.query("select report_community('homework',$1,'other','')",[hw]);
 await asUser(db,id(3));assert.equal((await db.query("select * from class_homework")).rows.length,0);
 await assert.rejects(db.query("select report_community('homework',$1,'other','')",[hw]));
 await assert.rejects(db.query("select moderate_class_homework($1)",[hw]));
 await asUser(db,id(4));await db.query("select moderate_class_homework($1)",[hw]);
 await asUser(db,id(1));assert.equal((await db.query("select * from class_homework")).rows.length,1);
 await assert.rejects(db.query("select save_class_homework($1,current_date,'Restore hidden',$2)",[id(20),hw]));
 for(let n=0;n<10;n++)await db.query("select report_community('profile',$1,'spam','')",[id(3)]);
 await assert.rejects(db.query("select report_community('profile',$1,'spam','')",[id(3)]),/rate_limit/);
 await asUser(db,id(2));await db.query("select delete_class_homework($1)",[other]);assert.equal((await db.query("select * from class_homework")).rows.length,0);
 await asUser(db,null);
 for(const sql of ["select * from people_list('search','Student')","select * from dm_inbox_v053()","select * from notification_feed_v053()","select * from class_homework","select * from community_reports"])await assert.rejects(db.query(sql));
 }finally{await db.close();}
});
