import Link from "next/link";
import {adminData} from "@/lib/admin-queries";
import {getCatalogOptions} from "@/lib/queries";
import {controlCopy,adminPage} from "@/lib/admin-control";
import type {Locale} from "@/lib/i18n";
import {AdminFilterForm} from "./admin-filter-form";
import {AdminStat,AdminFeed,AdminUserList,AdminUnavailable,AdminWidget,AdminPagination} from "./admin-data-ui";
export async function ActivityFilter({locale,classId}:{locale:Locale;classId?:string}){const {classes}=await getCatalogOptions(),t=controlCopy(locale);return <AdminFilterForm href="/admin/activity" key={classId??"all"}><label><span className="field-label">{t.classes}</span><select className="field" name="class" defaultValue={classId??""}><option value="">{t.all}</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></AdminFilterForm>;}
export async function ActivityStats({locale,classId}:{locale:Locale;classId?:string}){
 const data=await adminData("activity",{class:classId}),t=controlCopy(locale);if(!data)return <AdminUnavailable locale={locale}/>;
 const devices=new Map<string,number>(),browsers=new Map<string,number>();for(const a of data.agents){devices.set(a.device,(devices.get(a.device)??0)+a.count);browsers.set(a.browser,(browsers.get(a.browser)??0)+a.count);}
 return <><div className="admin-stats">{(["online","today","week"] as const).map(key=><AdminStat key={key} label={t[key]} value={data[key]}/>)}</div><div className="admin-grid">{[[t.devices,devices],[t.browsers,browsers]].map(([title,counts])=><AdminWidget title={title as string} key={title as string}><p>{t.deviceHint}</p><ul className="admin-list">{Array.from(counts as Map<string,number>).map(([name,count])=><li key={name}>{name} · {count}</li>)}</ul>{!(counts as Map<string,number>).size&&<p>{t.empty}</p>}</AdminWidget>)}</div></>;
}
export async function ActivityFeed({locale,classId,page:raw}:{locale:Locale;classId?:string;page?:string}){const page=adminPage(raw),rows=await adminData("feed",{class:classId,offset:page*25},locale);return <AdminWidget title={controlCopy(locale).recentActivity}><p>{controlCopy(locale).activityHint}</p><AdminFeed rows={rows} locale={locale}/><AdminPagination href="/admin/activity" params={{class:classId}} page={page} total={page*25+(rows?.length??0)+(rows?.length===25?1:0)}/></AdminWidget>;}
export async function OnlineUsers({locale,classId}:{locale:Locale;classId?:string}){const t=controlCopy(locale),data=await adminData("users",{class:classId,active:"online"});return <AdminWidget title={t.online}>{data?<><AdminUserList rows={data.rows} locale={locale}/>{data.total>25&&<Link className="text-link" href={"/admin/users?active=online"+(classId?"&class="+classId:"")}>{t.detail} · {data.total}</Link>}</>:<AdminUnavailable locale={locale}/>}</AdminWidget>;}
export async function ActivityClasses({locale,page:raw}:{locale:Locale;page?:string}){const page=adminPage(raw),data=await adminData("classes",{offset:page*25}),t=controlCopy(locale);return <AdminWidget title={t.classActivity}>{data?<><ul className="admin-list">{data.map(c=><li key={c.id}><Link href={"/admin/activity?class="+c.id} className="text-link">{c.name}</Link><p>{t.registered}: {c.registered} · {t.today}: {c.active}</p></li>)}</ul>{!data.length&&<p>{t.empty}</p>}<div className="admin-pagination">{page>0&&<Link href={"/admin/activity?classesPage="+(page-1)} className="text-link">{t.previous}</Link>}{data.length===25&&page<400&&<Link href={"/admin/activity?classesPage="+(page+1)} className="text-link">{t.next}</Link>}</div></>:<AdminUnavailable locale={locale}/>}</AdminWidget>;}
